package com.wbr.docs;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

// Only wired in the development profile — production services never expose API docs.
@OpenAPIDefinition(security = @SecurityRequirement(name = "bearerAuth"))
@SecurityScheme(name = "bearerAuth", type = SecuritySchemeType.HTTP, scheme = "bearer", bearerFormat = "JWT")
@Configuration
@Profile("development")
public class OpenApiConfiguration {

    @Value("${spring.application.name:service}")
    private String applicationName;

    // Populated from the consuming service's META-INF/build-info.properties,
    // generated by spring-boot-maven-plugin's build-info goal. Absent if not configured.
    @Autowired(required = false)
    private BuildProperties buildProperties;

    @Bean
    public OpenAPI openAPI() {
        Info info = new Info().title(applicationName + " API");
        if (buildProperties != null) {
            info.version(buildProperties.getVersion());
        }
        return new OpenAPI().info(info);
    }
}
