name: CD

on:
  workflow_dispatch: # Enables the manual trigger button
  push:
    branches: [main]

jobs:
  pipeline:
    permissions:
      id-token: write
      contents: read
    uses: WBR-Platform/wbr-github-workflows/.github/workflows/maven-library-cd.yml@main
